language: node_js
node_js: node
script: npm run build
deploy:
    provider: releases
    api_key:
        secure: KLgNto+oYdiS+svbt4DTttw1bGKmnuWXnOGBC42fQSjekU//JE/YwxV+GsDy6/QRWS+l83demi3z5yxHl9DMN6OB6tWUb2WfNEDezt4LhI9PegHceLGcp+8tEozQDOjiSCzjKW75lrJ1CKDkdzvYvJD9t3MbCEy+6XOBb0QinpOO60xx9S7c4uc1gdvCkgWnRWHnTlt5NI0r4CxfOjMWQqlU3vlqaDXLH6J+cHCvHJ6Z4G0cnRkOE4mqtcmFHmjBamiz4cuL3/Sj5HBnp2D5d/CDiOl3VRD0s2x5GtreNAE19XYvktbn2Ie4h5TsKb2tJjp9K4oMdko6GecN/rWhxw1edH3acRmxlxPFOBOOiUP4HYgPkp7J/gD249l36KN001XS8QFBv2oRKMc6H9w8ugttumGyVKZMoyWIyDWfoejH0RPzrk0iNeKmlnyOLdw0KP0wdv5Cq3F/ln76quvRcvwSS2vmhh3slNUC9oadDjqZZy7yKy1yfgryCKRN6Myx0sMMtKJEX2Wu9Auv4l7ofVs+emVT2xL1xTmGH24RFmoxNIn5LqoelAbS/FdNVac7FF8grqxwtu0whUBjBOLx75G15r1B6gqrrRdM8NyOc+y13aPdJLCl5fAu8gQMuUUka/VhoTnJA/1wUJcs8aehG/C2UMjcztJLbR78e7pZ16w=
    file: 'Publish/release.zip'
    skip_cleanup: true
    on:
        all_branches: true
        tags: true